### ISSUE TITLE
Hello, I use Bash to install this package  "install_BiasAdjustCXX.sh '' but I found a error :line 26: cmake: command not found

### ISSUE THREAD

**Issue by carldes** [btschwertfeger/BiasAdjustCXX#34]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by btschwertfeger** [comment]
```bash
error :line 26: cmake: command not found
```

is a hint by your bash environment that informs you about the absent of cmake.

Please make sure to to install CMake first, as described in the [documentation](https://biasadjustcxx.readthedocs.io/en/latest/src/quickstart.html) as well as in the README.rst.

Let me know if you need further assistance.

**Comment by carldes** [comment]
Thank you for your answer.
Best regard,
Carlo
Carlo Destouches, Ing. Civil, Msc Géosciencestel : 509 40408764 

    Le mardi 10 octobre 2023 à 08:18:07 UTC, Benjamin T. Schwertfeger ***@***.***> a écrit :  
 
 

error :line 26: cmake: command not found
is a hint by your bash environment that informs you about the absent of cmake.

Please make sure to to install CMake first, as described in the documentation as well as in the README.rst.

Let me know if you need further assistance.

**Comment by carldes** [comment]
Hi Benjamin,
I hope you are doing very well.
I want to use your script  in my work but i would to know  which of the two methods is faster (BiasAdjustCXX or python-cmethods module (to correct bias in 3d)I already try BiasAdjustCXX, i found a error when  i use you sh  example_all_methods.run.sh
You can see the error file attached.

Best regard,Carlo
Carlo Destouches, Ing. Civil, Msc Géosciencestel : 509 40408764 

    Le mardi 10 octobre 2023 à 11:10:22 UTC+2, Carlo Destouches ***@***.***> a écrit :  
 
 Thank you for your answer.
Best regard,
Carlo
Carlo Destouches, Ing. Civil, Msc Géosciencestel : 509 40408764 

    Le mardi 10 octobre 2023 à 08:18:07 UTC, Benjamin T. Schwertfeger ***@***.***> a écrit :  
 
 

error :line 26: cmake: command not found
is a hint by your bash environment that informs you about the absent of cmake.

Please make sure to to install CMake first, as described in the documentation as well as in the README.rst.

Let me know if you need further assistance.
